### ISSUE TITLE
Minor problem in error messages

### ISSUE THREAD

**Issue by nassibnassar** [Thomasdezeeuw/ini#20]
Thanks for this nicely designed library.  It seems that "syntax" is misspelled as "synthax" in error messages displayed to the user, e.g.:

`ini: synthax error on line 1: unexpected "=" after section closed
`

**Comment by Thomasdezeeuw** [comment]
Thanks for the report.

**Comment by Thomasdezeeuw** [comment]
This includes a breaking changes: renaming `IsSynthaxError` to `IsSyntaxError`.
