### ISSUE TITLE
Any plans to add support of environment variables?

### ISSUE THREAD

**Issue by ghost** [Thomasdezeeuw/ini#5]
Good day, @Thomasdezeeuw.

Don't you plan to add support of environment variables? In some packages values of the `${SOME_NAME}` form are replaced by their corresponding `os.Getenv` values.

That would be useful. What do you think?

**Comment by Thomasdezeeuw** [comment]
You mean in parsing? I'm not it's a good idea, people might not expect that.

**Comment by Thomasdezeeuw** [comment]
Do you have a good use case for it?

**Comment by ghost** [comment]
> You mean in parsing?

Yes, exactly.

> Do you have a good use case for it?

I'm looking for a config package for the [Goal Toolkit](https://github.com/colegion/goal). Support of env variables is a must for web apps when deploying to Heroku, Openshift, AWS, etc. Currently, I'm using a wrapper around your package + regular expressions + `ReplaceAllStringFunc`. But would prefer to replace it by a third party dependency instead of supporting my own wrapper.

**Comment by Thomasdezeeuw** [comment]
I think your current solution is actually the best one. Your package `goal/config` provides the configuration values, whether that's from a file or environment variables doesn't matter for the use of the package.

While the `ini` package only deals with parsing of ini formatted input. I used to have a `Load` function, that read and then parsed a config file, but I decided that was outside of the scope of the package to deal with files. And I feel the same way about dealing with environment variables.

I personally also use a config package to deal with environment and command line variables (which might have been a next request). So I'm going to close this, but if you have a different opinion please reopen it.
